{
 "title": "pktvisor from NS1",
 "description": "pktvisor metrics visualizations",
 "time": { "from": "now-24h", "to": "now-2m" },
 "templating": {
  "list": [
   {
    "name": "network",
    "query": "{\"find\":\"terms\",\"field\":\"tag.network.keyword\"}"
   },
   {
    "name": "pop",
    "query": "{\"find\":\"terms\",\"field\":\"tag.pop.keyword\", \"query\":\"tag.network.keyword:$network\"}"
   },
   {
    "name": "host",
    "query": "{\"find\":\"terms\",\"field\":\"tag.host.keyword\", \"query\":\"tag.network.keyword:$network AND pop:$pop\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "All Networks ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Packet Rates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{tag.network.keyword}} p95 In",
       "bucketAggs": [
        {
         "fake": true,
         "field": "tag.network.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_rates_pps_in_p95",
         "id": "1",
         "inlineScript": "_value/(($__interval_ms/1000)/60)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value/(($__interval_ms/1000)/60)"
          }
         },
         "type": "sum"
        }
       ],
       "timeField": "@timestamp"
      },
      {
       "alias": "{{tag.network.keyword}} p95 Out",
       "bucketAggs": [
        {
         "fake": true,
         "field": "tag.network.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_rates_pps_out_p95",
         "id": "1",
         "inlineScript": "_value/(($__interval_ms/1000)/60)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value/(($__interval_ms/1000)/60)"
          }
         },
         "type": "sum"
        }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Global Packet Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "p95 In",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.packets_rates_pps_in_p95",
       "id": "1",
       "inlineScript": "_value/(($__interval_ms/1000)/60)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value/(($__interval_ms/1000)/60)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "p95 Out",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.packets_rates_pps_out_p95",
       "id": "1",
       "inlineScript": "_value/(($__interval_ms/1000)/60)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value/(($__interval_ms/1000)/60)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "p99 In",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.packets_rates_pps_in_p99",
       "id": "1",
       "inlineScript": "_value/(($__interval_ms/1000)/60)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value/(($__interval_ms/1000)/60)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "p99 Out",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.packets_rates_pps_out_p99",
       "id": "1",
       "inlineScript": "_value/(($__interval_ms/1000)/60)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value/(($__interval_ms/1000)/60)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global DNS Query/Response per/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Queries",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_queries",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "Responses",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_replies",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global Packet Rates by POP p95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{tag.pop.keyword}} In",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.pop.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.packets_rates_pps_in_p95",
       "id": "1",
       "inlineScript": "_value/(($__interval_ms/1000)/60)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value/(($__interval_ms/1000)/60)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{tag.pop.keyword}} Out",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.pop.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.packets_rates_pps_out_p95",
       "id": "1",
       "inlineScript": "_value/(($__interval_ms/1000)/60)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value/(($__interval_ms/1000)/60)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global DNS Protocol Breakdown (In+Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "DNS TCP pps",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_tcp",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "DNS UDP pps",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_udp",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "DNS IPv4 pps",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_ipv4",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "DNS IPv6 pps",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_ipv6",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global DNS NX Attack View",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "NX Resp/s" }
   ],
   "targets": [
    {
     "alias": "{{tag.pop.keyword}} NX Resp/s",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.pop.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_nxdomain",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "Global QNAME Cardinality*",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_cardinality_qname",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "Global Src IP Cardinality*",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.packets_cardinality_src_ips_in",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global DNS Query/Response per/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "{{tag.pop.keyword}} Query/s",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.pop.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_queries",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{tag.pop.keyword}} Response/s",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tag.pop.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "http.dns_wire_packets_replies",
       "id": "1",
       "inlineScript": "_value / ($__interval_ms / 1000)",
       "meta": {},
       "settings": {
        "script": {
         "inline": "_value / ($__interval_ms / 1000)"
        }
       },
       "type": "sum"
      }
     ],
     "query": "tag.network.keyword:$network",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Global Top N",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Global Top QName2 QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_qname2_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qname2_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qname2_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top QName2",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top QName3 QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_qname3_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qname3_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qname3_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top QName3",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top SRVFAIL QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_srvfail_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_srvfail_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_srvfail_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_srvfail_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_srvfail_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_srvfail_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_srvfail_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_srvfail_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_srvfail_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top REFUSED QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_refused_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_refused_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_refused_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_refused_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_refused_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_refused_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_refused_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_refused_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_refused_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top NXDomain QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_nxdomain_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_nxdomain_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_nxdomain_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_nxdomain_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_nxdomain_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_nxdomain_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_nxdomain_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_nxdomain_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_nxdomain_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top IPv4 QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.packets_top_ipv4_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv4_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv4_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ipv4_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv4_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv4_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ipv4_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv4_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv4_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top IPv6 QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.packets_top_ipv6_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv6_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv6_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ipv6_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv6_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv6_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ipv6_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv6_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv6_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top QTypes QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_qtype_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qtype_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qtype_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qtype_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qtype_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qtype_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qtype_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qtype_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qtype_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top Geo QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.packets_top_geoLoc_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_geoLoc_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_geoLoc_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_geoLoc_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_geoLoc_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_geoLoc_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_geoLoc_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_geoLoc_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_geoLoc_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top ASN QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.packets_top_ASN_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ASN_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ASN_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ASN_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ASN_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ASN_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ASN_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ASN_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ASN_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top RCodes QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_rcode_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_rcode_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_rcode_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_rcode_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_rcode_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_rcode_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_rcode_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_rcode_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_rcode_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top DNS Slow Xact In QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_xact_in_top_slow_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_in_top_slow_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_top_slow_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_xact_in_top_slow_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_in_top_slow_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_top_slow_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_xact_in_top_slow_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_in_top_slow_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_top_slow_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top DNS Slow Xact Out QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_xact_out_top_slow_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_out_top_slow_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_top_slow_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_xact_out_top_slow_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_out_top_slow_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_top_slow_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_xact_out_top_slow_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_out_top_slow_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_top_slow_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Global Top DNS UDP Ports QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_udp_ports_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_udp_ports_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_udp_ports_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_udp_ports_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_udp_ports_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_udp_ports_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_udp_ports_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_udp_ports_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_udp_ports_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "POP Statistics: $pop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "pop",
   "collapsed": true,
   "panels": [
    {
     "title": "$pop Packet Rates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "p50 In",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_rates_pps_in_p50",
         "id": "1",
         "inlineScript": "_value/(($__interval_ms/1000)/60)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value/(($__interval_ms/1000)/60)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p50 Out",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_rates_pps_out_p50",
         "id": "1",
         "inlineScript": "_value/(($__interval_ms/1000)/60)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value/(($__interval_ms/1000)/60)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p99 In",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_rates_pps_in_p99",
         "id": "1",
         "inlineScript": "_value/(($__interval_ms/1000)/60)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value/(($__interval_ms/1000)/60)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p99 Out",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_rates_pps_out_p99",
         "id": "1",
         "inlineScript": "_value/(($__interval_ms/1000)/60)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value/(($__interval_ms/1000)/60)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop DNS NX Attack View",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "NX Resp/s" }
     ],
     "targets": [
      {
       "alias": "NX Resp/s",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_nxdomain",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "QNAME Cardinality*",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_cardinality_qname",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "Src IP Cardinality*",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_cardinality_src_ips_in",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": { "percents": [ "99" ] },
         "type": "percentiles"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Packet Protocol Breakdown (In+Out)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "TCP pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_tcp",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "UDP pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_udp",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "IPv4 pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_ipv4",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "IPv6 pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_ipv6",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop DNS Xact Times",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "µs", "label": "Xact In" }
     ],
     "targets": [
      {
       "alias": "p50 In",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_quantiles_us_p50",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p90 In",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_quantiles_us_p90",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p95 In",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_quantiles_us_p95",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p99 In",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_quantiles_us_p99",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p50 Out",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_quantiles_us_p50",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p90 Out",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_quantiles_us_p90",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p95 Out",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_quantiles_us_p95",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "p99 Out",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_quantiles_us_p99",
         "id": "1",
         "inlineScript": null,
         "meta": {},
         "settings": {},
         "type": "max"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop DNS Xact per/s In (server)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "tag.host.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_total",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop DNS Xact per/s Out (OS/ALIAS)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "tag.host.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_total",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop DNS Protocol Breakdown (In+Out)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "DNS TCP pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_tcp",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "DNS UDP pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_udp",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "DNS IPv4 pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_ipv4",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "DNS IPv6 pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_ipv6",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop DNS Failing RCODE Breakdown (In+Out)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "NXDOMAIN pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_nxdomain",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "SRVFAIL pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_srvfail",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "REFUSED pps",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_refused",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Sample Rate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "alias": "Sampled",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_deep_samples",
         "id": "1",
         "inlineScript": "_value / doc[\"http.packets_total\"].value",
         "meta": {},
         "pipelineAgg": "select metric",
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "select metric" }
         ],
         "settings": {
          "percents": [ "99" ],
          "script": {
           "inline": "_value / doc[\"http.packets_total\"].value"
          }
         },
         "type": "percentiles"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Hosts",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 5, "w": 4, "x": 2, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "bucketAggs": [
        {
         "fake": true,
         "field": "tag.host.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "host",
         "id": "1",
         "inlineScript": "_value / doc[\"http.packets_total\"].value",
         "meta": {},
         "pipelineAgg": "select metric",
         "pipelineVariables": [
          { "name": "var1", "pipelineAgg": "select metric" }
         ],
         "settings": {},
         "type": "count"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop DNS Query/Response per/s",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Query/s",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_queries",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "Response/s",
       "bucketAggs": [
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 0, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_wire_packets_replies",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "POP Top N: $pop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "repeat": "pop",
   "collapsed": true,
   "panels": [
    {
     "title": "$pop Top QName2 QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_qname2_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qname2_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qname2_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname2_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname2_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top QName3 QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_qname3_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qname3_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qname3_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qname3_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qname3_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top NXDomain QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_nxdomain_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_nxdomain_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_nxdomain_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_nxdomain_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_nxdomain_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_nxdomain_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_nxdomain_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_nxdomain_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_nxdomain_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top SRVFAIL QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_srvfail_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_srvfail_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_srvfail_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_srvfail_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_srvfail_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_srvfail_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_srvfail_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_srvfail_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_srvfail_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top REFUSED QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_refused_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_refused_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_refused_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_refused_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_refused_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_refused_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_refused_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_refused_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_refused_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top QTypes QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_qtype_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qtype_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qtype_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qtype_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qtype_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qtype_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_qtype_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_qtype_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_qtype_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top IPv4 QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.packets_top_ipv4_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv4_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv4_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ipv4_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv4_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv4_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ipv4_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv4_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv4_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top IPv6 QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.packets_top_ipv6_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv6_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv6_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ipv6_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv6_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv6_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ipv6_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ipv6_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ipv6_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top RCodes QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_rcode_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_rcode_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_rcode_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_rcode_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_rcode_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_rcode_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_rcode_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_rcode_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_rcode_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top Geo QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.packets_top_geoLoc_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_geoLoc_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_geoLoc_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_geoLoc_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_geoLoc_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_geoLoc_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_geoLoc_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_geoLoc_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_geoLoc_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top ASN QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.packets_top_ASN_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ASN_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ASN_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ASN_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ASN_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ASN_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.packets_top_ASN_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.packets_top_ASN_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.packets_top_ASN_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top DNS UDP Ports QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_top_udp_ports_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_udp_ports_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_udp_ports_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_udp_ports_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_udp_ports_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_udp_ports_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_top_udp_ports_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_top_udp_ports_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_top_udp_ports_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top DNS Slow Xact In QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_xact_in_top_slow_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_in_top_slow_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_top_slow_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_xact_in_top_slow_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_in_top_slow_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_top_slow_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_xact_in_top_slow_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_in_top_slow_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_in_top_slow_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "$pop Top DNS Slow Xact Out QPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "{{http.dns_xact_out_top_slow_0_name.keyword}} 1st",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_out_top_slow_0_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_top_slow_0_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_xact_out_top_slow_1_name.keyword}} 2nd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_out_top_slow_1_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_top_slow_1_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      },
      {
       "alias": "{{http.dns_xact_out_top_slow_2_name.keyword}} 3rd",
       "bucketAggs": [
        {
         "fake": true,
         "field": "http.dns_xact_out_top_slow_2_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "1", "size": "5" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "2",
         "settings": { "interval": "$__interval", "min_doc_count": 1, "trimEdges": 0 },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        {
         "field": "http.dns_xact_out_top_slow_2_estimate",
         "id": "1",
         "inlineScript": "_value / ($__interval_ms / 1000)",
         "meta": {},
         "settings": {
          "script": {
           "inline": "_value / ($__interval_ms / 1000)"
          }
         },
         "type": "sum"
        }
       ],
       "query": "tag.network.keyword:$network AND pop:$pop AND host:$host",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}