{
 "title": "pktvisor - Prometheus",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "L3 Protocols",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "packets_ipv4{instance=~\"$instance\"}",
     "legendFormat": "IPv4"
    },
    {
     "expr": "packets_ipv6{instance=~\"$instance\"}",
     "legendFormat": "IPv6"
    }
   ]
  },
  {
   "title": "L4 Protocols",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "packets_tcp{instance=~\"$instance\"}",
     "legendFormat": "TCP"
    },
    {
     "expr": "packets_udp{instance=~\"$instance\"}",
     "legendFormat": "UDP"
    },
    {
     "expr": "packets_other_l4{instance=~\"$instance\"}",
     "legendFormat": "Other L4"
    }
   ]
  },
  {
   "title": "Deep Inspection",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "packets_deep_samples{instance=~\"$instance\"}/packets_total{instance=~\"$instance\"}",
     "legendFormat": "sample_rate"
    }
   ]
  },
  {
   "title": "Avg Rate p95",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "packets_rates_pps_total{instance=~\"$instance\",quantile=\"0.95\"}"
    }
   ]
  },
  {
   "title": "Packet In/Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "packets_rates_pps_in{instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "p90 In"
    },
    {
     "expr": "packets_rates_pps_in{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "p99 In"
    },
    {
     "expr": "packets_rates_pps_out{instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "p90 Out"
    },
    {
     "expr": "packets_rates_pps_out{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "p99 Out"
    }
   ]
  },
  {
   "title": "L3/L4 Protocols",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "packets_ipv4{instance=~\"$instance\"}/60",
     "legendFormat": "IPv4"
    },
    {
     "expr": "packets_ipv6{instance=~\"$instance\"}/60",
     "legendFormat": "IPv6"
    },
    {
     "expr": "packets_tcp{instance=~\"$instance\"}/60",
     "legendFormat": "TCP"
    },
    {
     "expr": "packets_udp{instance=~\"$instance\"}/60",
     "legendFormat": "UDP"
    },
    {
     "expr": "packets_other_l4{instance=~\"$instance\"}/60",
     "legendFormat": "Other L4"
    }
   ]
  },
  {
   "title": "Top Geo IP/ASN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "packets_top_geoLoc{instance=~\"$instance\"}/60",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "packets_top_ASN{instance=~\"$instance\"}/60",
     "legendFormat": "ASN {{name}}"
    }
   ]
  },
  {
   "title": "Top IPv4",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (packets_top_ipv4{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top Geo",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (packets_top_geoLoc{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "packets_top_ipv4{instance=~\"$instance\"}/60",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "packets_top_ipv6{instance=~\"$instance\"}/60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top IPv6",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (packets_top_ipv6{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top ASN",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (packets_top_ASN{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Deep Inspection",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dns_wire_packets_deep_samples{instance=~\"$instance\"}/dns_wire_packets_total{instance=~\"$instance\"}",
     "legendFormat": "sample_rate"
    }
   ]
  },
  {
   "title": "Avg Rate p95",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "dns_rates_total{instance=~\"$instance\",quantile=\"0.95\"}"
    }
   ]
  },
  {
   "title": "QTypes",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "dns_top_qtype{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Result Codes",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "dns_top_rcode{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DNS Packets (In+Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "dns_rates_total{instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "dns_rates_total{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "DNS Protocols",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "dns_wire_packets_ipv4{instance=~\"$instance\"}/60",
     "legendFormat": "IPv4"
    },
    {
     "expr": "dns_wire_packets_ipv6{instance=~\"$instance\"}/60",
     "legendFormat": "IPv6"
    },
    {
     "expr": "dns_wire_packets_tcp{instance=~\"$instance\"}/60",
     "legendFormat": "TCP"
    },
    {
     "expr": "dns_wire_packets_udp{instance=~\"$instance\"}/60",
     "legendFormat": "UDP"
    }
   ]
  },
  {
   "title": "DNS Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "dns_xact_in_total{instance=~\"$instance\"}/60",
     "legendFormat": "Xact In (local server)"
    },
    {
     "expr": "dns_xact_out_total{instance=~\"$instance\"}/60",
     "legendFormat": "Xact Out (remote server)"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "dns_wire_packets_nxdomain{instance=~\"$instance\"}/60",
     "legendFormat": "NXDOMAIN"
    },
    {
     "expr": "dns_wire_packets_srvfail{instance=~\"$instance\"}/60",
     "legendFormat": "SRVFAIL"
    },
    {
     "expr": "dns_wire_packets_refused{instance=~\"$instance\"}/60",
     "legendFormat": "REFUSED"
    }
   ]
  },
  {
   "title": "Top DNS Names",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "dns_top_qname2{instance=~\"$instance\"}/60",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "dns_top_qname3{instance=~\"$instance\"}/60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top QName2",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (dns_top_qname2{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top QName2",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (dns_top_qname2{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top DNS RCodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "dns_top_rcode{instance=~\"$instance\"}/60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top RCodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (dns_top_rcode{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Top QTypes",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 17, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (name) (dns_top_qtype{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "DNS Transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "dns_xact_in_quantiles_us{instance=~\"$instance\",quantile=\"0.95\"}",
     "legendFormat": "In p95"
    },
    {
     "expr": "dns_xact_out_quantiles_us{instance=~\"$instance\",quantile=\"0.95\"}",
     "legendFormat": "Out p95"
    },
    {
     "expr": "dns_xact_out_quantiles_us{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "Out p99"
    },
    {
     "expr": "dns_xact_in_quantiles_us{instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "In p99"
    }
   ]
  },
  {
   "title": "Top DNS QTypes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "dns_top_qtype{instance=~\"$instance\"}/60",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top DNS Ports",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "dns_top_udp_ports{instance=~\"$instance\"}/60",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}