FROM ns1labs/clang-toolchain:latest AS cppbuild
ARG REQUIRE="make cmake python3 py3-pip perl git bash libexecinfo-static libexecinfo-dev"

RUN apk add --no-cache ${REQUIRE}

RUN ln -s /usr/local/bin/clang /usr/local/bin/cc \
    && ln -s /usr/local/bin/clang /usr/local/bin/gcc \
    && ln -s /usr/local/bin/clang++ /usr/local/bin/c++ \
    && ln -s /usr/local/bin/clang++ /usr/local/bin/g++ \
    && ln -s /usr/local/bin/clang-cpp /usr/local/bin/cpp \
    && pip install conan \
    && conan profile new --detect default

COPY . /pktvisor-src/

WORKDIR /tmp/build
RUN \
    conan profile new --detect default && \
    conan config set general.revisions_enabled=1

RUN \
    PKG_CONFIG_PATH=/local/lib/pkgconfig cmake -DCMAKE_BUILD_TYPE=Release /pktvisor-src && \
    make all test -j 4

FROM alpine:latest AS runtime

COPY --from=cppbuild /build/bin/pktvisord /pktvisord

ENTRYPOINT [ "/pktvisord" ]
