name: 'docker'
author: 'Everton Haise Taques <everton.taques@encora.com>'
description: 'NS1 Labs'

inputs:
  context:
    description: "Docker build context"
    required: true
    default: "./"

  symbol_url:
    description: "symbol url"
    required: true
    default: ""
    
  setting:
    description: "custom settings for conan"
    required: false
    default: ""
    
  build_type:
    description: "build type"
    required: true
    default: "Debug"
    
  asan:
    description: "asan"
    required: true
    default: "ON"

  file:
    description: "Dockerfile used to build the image"
    required: true
    default: "./Dockerfile"

runs:
    using: 'docker'
    image: 'Dockerfile'
  
