#!/usr/bin/env bash

(
  cat <<END
server:
  log_level: info
  http_listen_port: 20853
prometheus:
  global:
    scrape_interval: 1m
  configs:
    - name: pktvisor
      scrape_configs:
        - job_name: grafana_agent
          static_configs:
            - targets: ['127.0.0.1:20853']
        - job_name: pktvisor
          honor_timestamps: true
          honor_labels: true
          scrape_interval: 1m
          scrape_timeout: 5s
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets:
                - localhost:10853
      remote_write:
          - url: $REMOTE_URL
            basic_auth:
              username: $USERNAME
              password: $PASSWORD
END
) >/etc/agent/agent.yaml

exec runsvdir /etc/service/
